[2019-04-08T10:37:05.163] [ERROR] dateFileLog - Error: Not found this user by userAID Laoyadan.
    at callback_getUser (D:\work\TOOLSWEB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:106:24)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:131:4
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.safeCallback (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:130:11)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:144:11)
    at Query.<anonymous> (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:564:33)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2019-04-08T10:37:05.166] [ERROR] dateFileLog - Error: Not found this user by userAID Laoyadan.
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
