[2019-04-09T09:38:52.160] [ERROR] dateFileLog - Error: Not found this user by userAID Lyd.
    at callback_getUser (D:\work\TOOLSWEB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:106:24)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:131:4
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.safeCallback (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:130:11)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:144:11)
    at Query.<anonymous> (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:564:33)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2019-04-09T09:38:52.164] [ERROR] dateFileLog - Error: Not found this user by userAID Lyd.
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-04-09T09:38:53.045] [ERROR] dateFileLog - Error: Not found this user by userAID Lyd.
    at callback_getUser (D:\work\TOOLSWEB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:106:24)
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:131:4
    at Object.exports.safeSuccess (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:96:13)
    at Object.exports.safeCallback (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:130:11)
    at Object.exports.handleResult (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjError.js:144:11)
    at Query.<anonymous> (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:564:33)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\work\TOOLSWEB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2019-04-09T09:38:53.048] [ERROR] dateFileLog - Error: Not found this user by userAID Lyd.
    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-04-09T15:42:30.352] [ERROR] dateFileLog - Error: Error: 执行SQL语句不能为空！<br> &nbsp; &nbsp;at Object.checkOptions (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.util.js:76:16)<br> &nbsp; &nbsp;at Object.exec (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:456:22)<br> &nbsp; &nbsp;at module.exports (D:\work\TOOLSWEB\toolsWeb\biz\PM\getSQLDBData.{m}.js:189:19)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\TOOLSWEB\node_modules\express\lib\router\layer.js:95:5)

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-04-09T15:49:16.692] [ERROR] dateFileLog - Error: Error: 执行SQL语句不能为空！<br> &nbsp; &nbsp;at Object.checkOptions (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.util.js:76:16)<br> &nbsp; &nbsp;at Object.exec (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:456:22)<br> &nbsp; &nbsp;at module.exports (D:\work\TOOLSWEB\toolsWeb\biz\PM\getSQLDBData.{m}.js:189:19)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\TOOLSWEB\node_modules\express\lib\router\layer.js:95:5)

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-04-09T15:49:21.074] [ERROR] dateFileLog - Error: Error: 执行SQL语句不能为空！<br> &nbsp; &nbsp;at Object.checkOptions (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.util.js:76:16)<br> &nbsp; &nbsp;at Object.exec (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:456:22)<br> &nbsp; &nbsp;at module.exports (D:\work\TOOLSWEB\toolsWeb\biz\PM\getSQLDBData.{m}.js:189:19)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\TOOLSWEB\node_modules\express\lib\router\layer.js:95:5)

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-04-09T16:52:05.248] [ERROR] dateFileLog - Error: Error: 执行SQL语句不能为空！<br> &nbsp; &nbsp;at Object.checkOptions (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.util.js:76:16)<br> &nbsp; &nbsp;at Object.exec (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:456:22)<br> &nbsp; &nbsp;at module.exports (D:\work\TOOLSWEB\toolsWeb\biz\PM\getSQLDBData.{m}.js:189:19)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\TOOLSWEB\node_modules\express\lib\router\layer.js:95:5)

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2019-04-09T16:52:35.419] [ERROR] dateFileLog - Error: Error: 执行SQL语句不能为空！<br> &nbsp; &nbsp;at Object.checkOptions (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.util.js:76:16)<br> &nbsp; &nbsp;at Object.exec (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:456:22)<br> &nbsp; &nbsp;at module.exports (D:\work\TOOLSWEB\toolsWeb\biz\PM\getSQLDBData.{m}.js:189:19)<br> &nbsp; &nbsp;at buildData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:187:6)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:129:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.cache.js:78:4)<br> &nbsp; &nbsp;at loadData (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:123:15)<br> &nbsp; &nbsp;at rrnmv (D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:120:2)<br> &nbsp; &nbsp;at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjMVC.js:223:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\work\TOOLSWEB\node_modules\express\lib\router\layer.js:95:5)

    at D:\work\TOOLSWEB\yujiang.Foil.Node\src\yjREST.engine.remote.superagent.js:43:34
    at Request.callback (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:797:3)
    at IncomingMessage.<anonymous> (D:\work\TOOLSWEB\node_modules\superagent\lib\node\index.js:990:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
