[2017-07-25 09:34:25.419] [ERROR] dateFileLog - C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOutputLower.js:179
                    },
                     ^
SyntaxError: Unexpected token ,
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.foundFile (C:\NB\yujiang.Foil.Node\src\yjApp.js:192:7)
[2017-07-25 09:53:00.363] [ERROR] dateFileLog - TypeError: Cannot read property 'totalValue' of undefined
    at success (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOutputLower.js:66:43)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query._callback (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at Query.Sequence.end (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NB\node_modules\mysql\lib\Connection.js:82:28)
[2017-07-25 09:54:00.322] [ERROR] dateFileLog - TypeError: Cannot read property 'totalValue' of undefined
    at success (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOutputLower.js:66:43)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query._callback (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at Query.Sequence.end (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NB\node_modules\mysql\lib\Connection.js:82:28)
[2017-07-25 09:55:00.336] [ERROR] dateFileLog - TypeError: Cannot read property 'totalValue' of undefined
    at success (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOutputLower.js:66:43)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query._callback (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at Query.Sequence.end (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NB\node_modules\mysql\lib\Connection.js:82:28)
[2017-07-25 10:13:00.256] [ERROR] dateFileLog - TypeError: Cannot read property 'totalValue' of undefined
    at success (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOutputLower.js:69:57)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query._callback (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at Query.Sequence.end (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NB\node_modules\mysql\lib\Connection.js:82:28)
[2017-07-25 10:14:00.262] [ERROR] dateFileLog - TypeError: Cannot read property 'totalValue' of undefined
    at success (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOutputLower.js:69:57)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query._callback (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at Query.Sequence.end (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NB\node_modules\mysql\lib\Connection.js:82:28)
[2017-07-25 10:50:53.383] [ERROR] dateFileLog - Error: ReferenceError: iniFormaterrLocalTimeNowStr is not defined<br> &nbsp; &nbsp;at paramIniTenMinutes (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:88:22)<br> &nbsp; &nbsp;at module.exports (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:11:16)<br> &nbsp; &nbsp;at buildData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at C:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (C:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (C:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at C:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (C:\NB\node_modules\express\lib\router\route.js:131:13)

    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
[2017-07-25 10:51:36.239] [ERROR] dateFileLog - Error: ReferenceError: yjDateTime is not defined<br> &nbsp; &nbsp;at paramIniTenMinutes (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:114:17)<br> &nbsp; &nbsp;at module.exports (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:11:16)<br> &nbsp; &nbsp;at buildData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at C:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (C:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (C:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at C:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (C:\NB\node_modules\express\lib\router\route.js:131:13)

    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
[2017-07-25 10:52:19.852] [ERROR] dateFileLog - { Error: ER_BAD_FIELD_ERROR: Unknown column 'ddh.CatchTime' in 'where clause'
    at Query.Sequence._packetToError (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
    --------------------
    at Protocol._enqueue (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (C:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at success (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (C:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:280:14)
    at Ping.runBound [as _callback] (domain.js:293:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0 }
[2017-07-25 10:52:19.860] [ERROR] dateFileLog - Error: ER_BAD_FIELD_ERROR: Unknown column 'ddh.CatchTime' in 'where clause'
    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
[2017-07-25 11:01:02.455] [ERROR] dateFileLog - Error: 错误的参数类型！只能是阵列。
    at Object.checkOptions (C:\NB\yujiang.Foil.Node\src\yjDBService.util.js:84:16)
    at Object.exec (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:110:26)
    at module.exports (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:33:17)
    at buildData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)
    at C:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5
    at Object.module.exports.read (C:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)
    at loadData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)
    at rrnmv (C:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)
    at C:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4
    at Layer.handle [as handle_request] (C:\NB\node_modules\express\lib\router\layer.js:95:5)
[2017-07-25 11:01:02.464] [ERROR] dateFileLog - Error: 错误的参数类型！只能是阵列。
    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
[2017-07-25 11:01:40.985] [ERROR] dateFileLog - Error: 错误的参数类型！只能是阵列。
    at Object.checkOptions (C:\NB\yujiang.Foil.Node\src\yjDBService.util.js:84:16)
    at Object.exec (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:110:26)
    at module.exports (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:32:17)
    at buildData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)
    at C:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5
    at Object.module.exports.read (C:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)
    at loadData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)
    at rrnmv (C:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)
    at C:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4
    at Layer.handle [as handle_request] (C:\NB\node_modules\express\lib\router\layer.js:95:5)
[2017-07-25 11:01:40.998] [ERROR] dateFileLog - Error: 错误的参数类型！只能是阵列。
    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
[2017-07-25 11:01:41.819] [ERROR] dateFileLog - Error: 错误的参数类型！只能是阵列。
    at Object.checkOptions (C:\NB\yujiang.Foil.Node\src\yjDBService.util.js:84:16)
    at Object.exec (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:110:26)
    at module.exports (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:32:17)
    at buildData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)
    at C:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5
    at Object.module.exports.read (C:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)
    at loadData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)
    at rrnmv (C:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)
    at C:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4
    at Layer.handle [as handle_request] (C:\NB\node_modules\express\lib\router\layer.js:95:5)
[2017-07-25 11:01:41.826] [ERROR] dateFileLog - Error: 错误的参数类型！只能是阵列。
    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
[2017-07-25 13:30:08.205] [ERROR] dateFileLog - Error: ReferenceError: dateTime is not defined<br> &nbsp; &nbsp;at module.exports (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:27:45)<br> &nbsp; &nbsp;at buildData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at C:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (C:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (C:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (C:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at C:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (C:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (C:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
[2017-07-25 16:03:25.777] [ERROR] dateFileLog - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
    at Query.Sequence._packetToError (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (C:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at success (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (C:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:280:14)
    at Ping.runBound [as _callback] (domain.js:293:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
[2017-07-25 16:03:25.800] [ERROR] dateFileLog - Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1
    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
