[2017-07-26 09:00:10.793] [ERROR] dateFileLog - { Error: Invalid login: 535 5.7.3 Authentication unsuccessful
    at SMTPConnection._formatError (C:\NB\node_modules\nodemailer\node_modules\nodemailer-smtp-pool\node_modules\smtp-connection\lib\smtp-connection.js:528:15)
    at SMTPConnection._actionAUTHComplete (C:\NB\node_modules\nodemailer\node_modules\nodemailer-smtp-pool\node_modules\smtp-connection\lib\smtp-connection.js:1231:30)
    at SMTPConnection.<anonymous> (C:\NB\node_modules\nodemailer\node_modules\nodemailer-smtp-pool\node_modules\smtp-connection\lib\smtp-connection.js:1199:14)
    at SMTPConnection._processResponse (C:\NB\node_modules\nodemailer\node_modules\nodemailer-smtp-pool\node_modules\smtp-connection\lib\smtp-connection.js:669:16)
    at SMTPConnection._onData (C:\NB\node_modules\nodemailer\node_modules\nodemailer-smtp-pool\node_modules\smtp-connection\lib\smtp-connection.js:493:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:551:20)
  code: 'EAUTH',
  response: '535 5.7.3 Authentication unsuccessful',
  responseCode: 535,
  command: 'AUTH LOGIN' }
[2017-07-26 10:17:00.464] [ERROR] dateFileLog - ReferenceError: paramIniTenMinutes is not defined
    at simillumData (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:23:16)
    at triggerData (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:20:5)
    at Job.job (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:14:9)
    at Job.invoke (C:\NB\node_modules\node-schedule\lib\schedule.js:175:10)
    at Timeout._onTimeout (C:\NB\node_modules\node-schedule\lib\schedule.js:456:11)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-07-26 10:18:00.409] [ERROR] dateFileLog - ReferenceError: paramIniTenMinutes is not defined
    at simillumData (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:23:16)
    at triggerData (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:20:5)
    at Job.job (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:14:9)
    at Job.invoke (C:\NB\node_modules\node-schedule\lib\schedule.js:175:10)
    at Timeout._onTimeout (C:\NB\node_modules\node-schedule\lib\schedule.js:456:11)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
    at listOnTimeoutNT (timers.js:270:26)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
[2017-07-26 10:19:00.459] [ERROR] dateFileLog - ReferenceError: paramIniTenMinutes is not defined
    at simillumData (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:23:16)
    at triggerData (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:20:5)
    at Job.job (C:\NB\tm.FGEMS\bizServer\biz\auto\AlarmOptimizer.js:14:9)
    at Job.invoke (C:\NB\node_modules\node-schedule\lib\schedule.js:175:10)
    at Timeout._onTimeout (C:\NB\node_modules\node-schedule\lib\schedule.js:456:11)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-07-26 15:35:06.801] [ERROR] dateFileLog - ReferenceError: timeTemp is not defined
    at success (C:\NB\tm.FGEMS\bizServer\biz\warning\getDeviceAbnormal.{m}.js:90:51)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:280:14)
    at Query.runBound [as _callback] (domain.js:293:12)
    at Query.Sequence.end (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
[2017-07-26 15:35:06.812] [ERROR] dateFileLog - Error: timeTemp is not defined
    at Request.<anonymous> (C:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (C:\NB\node_modules\restler\lib\restler.js:220:12)
    at C:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB\node_modules\restler\lib\restler.js:195:29)
    at C:\NB\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB\node_modules\restler\lib\restler.js:147:14)
[2017-07-26 16:23:00.446] [ERROR] dateFileLog - TypeError: Cannot read property 'Name' of undefined
    at C:\NB\tm.FGEMS\bizServer\biz\auto\SendAlarmEmail.js:33:41
    at Object.async.whilst (C:\NB\node_modules\async\lib\async.js:678:13)
    at success (C:\NB\tm.FGEMS\bizServer\biz\auto\SendAlarmEmail.js:28:23)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query._callback (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at Query.Sequence.end (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
[2017-07-26 16:24:00.438] [ERROR] dateFileLog - TypeError: Cannot read property 'Name' of undefined
    at C:\NB\tm.FGEMS\bizServer\biz\auto\SendAlarmEmail.js:33:41
    at Object.async.whilst (C:\NB\node_modules\async\lib\async.js:678:13)
    at success (C:\NB\tm.FGEMS\bizServer\biz\auto\SendAlarmEmail.js:28:23)
    at Object.exports.safeSuccess (C:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query._callback (C:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at Query.Sequence.end (C:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
    at Protocol._parsePacket (C:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
