[2018-08-30 08:56:31.611] [ERROR] dateFileLog - [Error: Cannot POST /biz/MSInfo/updateSP?SPID=52&amp;downloadNum=1
]
Error: Cannot POST /biz/MSInfo/updateSP?SPID=52&amp;downloadNum=1

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 08:57:15.833] [ERROR] dateFileLog - [Error: Cannot POST /biz/MSInfo/updateSP?SPID=52&amp;downloadNum=1
]
Error: Cannot POST /biz/MSInfo/updateSP?SPID=52&amp;downloadNum=1

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 09:00:20.869] [ERROR] dateFileLog - { [Error: D:\NB\tm.FGEMS\webServer\app\MSFactory\showMSFactory.{v}.ejs:1
 >> 1| <% layout('./MSFactory.ejs') -%> 
    2| <% block('AgentAdmin',partial("./AgentAdmin.ejs")) -%> 
    3| <% block('AgentAdd',partial("./AgentAdd.ejs")) -%> 
    4| <% block('AgentSP',partial("./AgentSP.ejs")) -%> 

Could not find partial ./AgentSPAdmin.ejs]
  path: 'D:\\NB\\tm.FGEMS\\webServer\\app\\MSFactory\\showMSFactory.{v}.ejs' }
Error: D:\NB\tm.FGEMS\webServer\app\MSFactory\showMSFactory.{v}.ejs:1
 >> 1| <% layout('./MSFactory.ejs') -%> 
    2| <% block('AgentAdmin',partial("./AgentAdmin.ejs")) -%> 
    3| <% block('AgentAdd',partial("./AgentAdd.ejs")) -%> 
    4| <% block('AgentSP',partial("./AgentSP.ejs")) -%> 

Could not find partial ./AgentSPAdmin.ejs
    at Object.partial (D:\NB\node_modules\ejs-locals\index.js:311:11)
    at eval (eval at <anonymous> (D:\NB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:346)
    at eval (eval at <anonymous> (D:\NB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:1464)
    at D:\NB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:250:15
    at Object.exports.render (D:\NB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:288:13)
    at Object.exports.renderFile (D:\NB\node_modules\ejs-locals\node_modules\ejs\lib\ejs.js:318:20)
    at View.module.exports [as engine] (D:\NB\node_modules\ejs-locals\index.js:85:7)
    at View.render (D:\NB\node_modules\express\lib\view.js:126:8)
    at tryRender (D:\NB\node_modules\express\lib\application.js:639:10)
    at EventEmitter.render (D:\NB\node_modules\express\lib\application.js:591:3)
[2018-08-30 09:13:31.416] [ERROR] dateFileLog - [Error: Not found this user.]
Error: Not found this user.
    at callback_getUser (D:\NB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:106:17)
    at D:\NB\yujiang.Foil.Node\src\yjError.js:134:4
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.safeCallback (D:\NB\yujiang.Foil.Node\src\yjError.js:133:11)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:148:11)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
    at Query.runBound [as _callback] (domain.js:300:12)
    at Query.Sequence.end (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-08-30 09:13:31.419] [ERROR] dateFileLog - [Error: 没有找到此用户。]
Error: 没有找到此用户。
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 09:15:50.462] [ERROR] dateFileLog - [Error: Password is not correct.]
Error: Password is not correct.
    at callback_getUser (D:\NB\yujiang.Foil.Node.BizServer\biz\account\checkLogin.js:150:17)
    at D:\NB\yujiang.Foil.Node\src\yjError.js:134:4
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.safeCallback (D:\NB\yujiang.Foil.Node\src\yjError.js:133:11)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:148:11)
    at Query.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:287:14)
    at Query.runBound [as _callback] (domain.js:300:12)
    at Query.Sequence.end (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
[2018-08-30 09:15:50.463] [ERROR] dateFileLog - [Error: 密码不对。]
Error: 密码不对。
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:21:12.739] [ERROR] dateFileLog - [Error: Error: Unexpected data type<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.$getDataForEcrypt (D:\NB\node_modules\node-rsa\src\NodeRSA.js:265:19)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.sign (D:\NB\node_modules\node-rsa\src\NodeRSA.js:196:32)<br> &nbsp; &nbsp;at Object.yjSecurity.Diffie-Hellman.sign (D:\NB\yujiang.Foil.Node\src\yjSecurity.js:292:28)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:18:46)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)
]
Error: Error: Unexpected data type<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.$getDataForEcrypt (D:\NB\node_modules\node-rsa\src\NodeRSA.js:265:19)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.sign (D:\NB\node_modules\node-rsa\src\NodeRSA.js:196:32)<br> &nbsp; &nbsp;at Object.yjSecurity.Diffie-Hellman.sign (D:\NB\yujiang.Foil.Node\src\yjSecurity.js:292:28)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:18:46)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:24:24.526] [ERROR] dateFileLog - [Error: Error: Unexpected data type<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.$getDataForEcrypt (D:\NB\node_modules\node-rsa\src\NodeRSA.js:265:19)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.sign (D:\NB\node_modules\node-rsa\src\NodeRSA.js:196:32)<br> &nbsp; &nbsp;at Object.yjSecurity.Diffie-Hellman.sign (D:\NB\yujiang.Foil.Node\src\yjSecurity.js:292:28)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:18:46)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)
]
Error: Error: Unexpected data type<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.$getDataForEcrypt (D:\NB\node_modules\node-rsa\src\NodeRSA.js:265:19)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.sign (D:\NB\node_modules\node-rsa\src\NodeRSA.js:196:32)<br> &nbsp; &nbsp;at Object.yjSecurity.Diffie-Hellman.sign (D:\NB\yujiang.Foil.Node\src\yjSecurity.js:292:28)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:18:46)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:27:04.919] [ERROR] dateFileLog - [Error: Error: Unexpected data type<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.$getDataForEcrypt (D:\NB\node_modules\node-rsa\src\NodeRSA.js:265:19)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.sign (D:\NB\node_modules\node-rsa\src\NodeRSA.js:196:32)<br> &nbsp; &nbsp;at Object.yjSecurity.Diffie-Hellman.sign (D:\NB\yujiang.Foil.Node\src\yjSecurity.js:292:28)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:18:46)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)
]
Error: Error: Unexpected data type<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.$getDataForEcrypt (D:\NB\node_modules\node-rsa\src\NodeRSA.js:265:19)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.sign (D:\NB\node_modules\node-rsa\src\NodeRSA.js:196:32)<br> &nbsp; &nbsp;at Object.yjSecurity.Diffie-Hellman.sign (D:\NB\yujiang.Foil.Node\src\yjSecurity.js:292:28)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:18:46)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:27:58.898] [ERROR] dateFileLog - [Error: Error: Unexpected data type<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.$getDataForEcrypt (D:\NB\node_modules\node-rsa\src\NodeRSA.js:265:19)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.sign (D:\NB\node_modules\node-rsa\src\NodeRSA.js:196:32)<br> &nbsp; &nbsp;at Object.yjSecurity.Diffie-Hellman.sign (D:\NB\yujiang.Foil.Node\src\yjSecurity.js:292:28)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:18:46)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)
]
Error: Error: Unexpected data type<br> &nbsp; &nbsp;at Error (native)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.$getDataForEcrypt (D:\NB\node_modules\node-rsa\src\NodeRSA.js:265:19)<br> &nbsp; &nbsp;at NodeRSA.module.exports.NodeRSA.sign (D:\NB\node_modules\node-rsa\src\NodeRSA.js:196:32)<br> &nbsp; &nbsp;at Object.yjSecurity.Diffie-Hellman.sign (D:\NB\yujiang.Foil.Node\src\yjSecurity.js:292:28)<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:18:46)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:31:03.569] [ERROR] dateFileLog - [Error: ReferenceError: UserAID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:25)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: UserAID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:25)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:33:48.191] [ERROR] dateFileLog - [Error: ReferenceError: PWenc is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:33)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: PWenc is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:33)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:35:26.989] [ERROR] dateFileLog - [Error: ReferenceError: PWenc is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:33)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: PWenc is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:33)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:35:59.091] [ERROR] dateFileLog - [Error: ReferenceError: Name is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:39)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: Name is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:39)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:37:21.722] [ERROR] dateFileLog - [Error: ReferenceError: UserFID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:52)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: UserFID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:52)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:39:04.539] [ERROR] dateFileLog - [Error: ReferenceError: UserFID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:52)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: UserFID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:64:52)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:40:57.026] [ERROR] dateFileLog - [Error: ReferenceError: Acount is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:116:30)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: Acount is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:116:30)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:43:37.806] [ERROR] dateFileLog - { [Error: ER_BAD_FIELD_ERROR: Unknown column 'Acount' in 'order clause']
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0 }
Error: ER_BAD_FIELD_ERROR: Unknown column 'Acount' in 'order clause'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-30 16:43:37.810] [ERROR] dateFileLog - [Error: ER_BAD_FIELD_ERROR: Unknown column 'Acount' in 'order clause']
Error: ER_BAD_FIELD_ERROR: Unknown column 'Acount' in 'order clause'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:44:33.727] [ERROR] dateFileLog - { [Error: ER_BAD_FIELD_ERROR: Unknown column 'Acount' in 'order clause']
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0 }
Error: ER_BAD_FIELD_ERROR: Unknown column 'Acount' in 'order clause'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-30 16:44:33.728] [ERROR] dateFileLog - [Error: ER_BAD_FIELD_ERROR: Unknown column 'Acount' in 'order clause']
Error: ER_BAD_FIELD_ERROR: Unknown column 'Acount' in 'order clause'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:51:07.172] [ERROR] dateFileLog - [Error: ReferenceError: Acount is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:116:30)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: Acount is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:116:30)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:52:52.633] [ERROR] dateFileLog - { [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1]
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-30 16:52:52.635] [ERROR] dateFileLog - [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1]
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 16:52:52.685] [ERROR] dateFileLog - [Error: Can't set headers after they are sent.]
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (D:\NB\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (D:\NB\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (D:\NB\node_modules\express\lib\response.js:151:21)
    at proc_success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:111:13)
    at Object.sender.success (D:\NB\yujiang.Foil.Node\src\yjMVC.js:239:8)
    at yjDBService.exec.success (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:121:16)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
[2018-08-30 16:57:27.965] [ERROR] dateFileLog - { [Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1]
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  index: 0 }
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-30 17:47:45.663] [ERROR] dateFileLog - [Error: ReferenceError: UserOID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:28:17)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: UserOID is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addAgent.{post}.{m}.js:28:17)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 18:14:31.726] [ERROR] dateFileLog - [Error: ReferenceError: FInfo is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addUser.{post}.{m}.js:24:57)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)
]
Error: ReferenceError: FInfo is not defined<br> &nbsp; &nbsp;at module.exports (D:\NB\tm.FGEMS\bizServer\biz\MSFactory\addUser.{post}.{m}.js:24:57)<br> &nbsp; &nbsp;at buildData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:256:6)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:198:5<br> &nbsp; &nbsp;at Object.module.exports.read (D:\NB\yujiang.Foil.Node\src\yjMVC.cache.js:80:4)<br> &nbsp; &nbsp;at loadData (D:\NB\yujiang.Foil.Node\src\yjMVC.js:192:15)<br> &nbsp; &nbsp;at rrnmv (D:\NB\yujiang.Foil.Node\src\yjMVC.js:188:3)<br> &nbsp; &nbsp;at D:\NB\yujiang.Foil.Node\src\yjMVC.js:290:4<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\NB\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\NB\node_modules\express\lib\router\route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\NB\node_modules\express\lib\router\route.js:112:3)

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 18:23:44.296] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '7HD016' for key 'Acount'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '7HD016' for key 'Acount'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-30 18:23:44.301] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '7HD016' for key 'Acount']
Error: ER_DUP_ENTRY: Duplicate entry '7HD016' for key 'Acount'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 18:23:44.304] [ERROR] dateFileLog - { [Error: ER_DUP_ENTRY: Duplicate entry '016' for key 'UserAID'] code: 'ER_DUP_ENTRY', errno: 1062, sqlState: '23000', index: 0 }
Error: ER_DUP_ENTRY: Duplicate entry '016' for key 'UserAID'
    at Query.Sequence._packetToError (D:\NB\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
    at Query.ErrorPacket (D:\NB\node_modules\mysql\lib\protocol\sequences\Query.js:82:18)
    at Protocol._parsePacket (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (D:\NB\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\NB\node_modules\mysql\lib\Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    --------------------
    at Protocol._enqueue (D:\NB\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at PoolConnection.Connection.query (D:\NB\node_modules\mysql\lib\Connection.js:185:25)
    at doQuery (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:128:25)
    at getConnection.success (D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:119:13)
    at Object.exports.safeSuccess (D:\NB\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (D:\NB\yujiang.Foil.Node\src\yjError.js:154:12)
    at D:\NB\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:57:11
    at Ping.onPing (D:\NB\node_modules\mysql\lib\Pool.js:94:5)
    at bound (domain.js:287:14)
    at Ping.runBound [as _callback] (domain.js:300:12)
[2018-08-30 18:23:44.306] [ERROR] dateFileLog - [Error: ER_DUP_ENTRY: Duplicate entry '016' for key 'UserAID']
Error: ER_DUP_ENTRY: Duplicate entry '016' for key 'UserAID'
    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
[2018-08-30 18:25:59.126] [ERROR] dateFileLog - [Error: Cannot POST /biz/MSFactory/authUsers?UserOID=0830182551&amp;FID=7HD&amp;AID=018&amp;Account=7HD018&amp;FName=%E6%B5%B7%E8%BE%BE&amp;AName=888&amp;Contact=888&amp;Address=888&amp;AInfo=888&amp;OpenUser=1&amp;VidDate=2018-09-01&amp;IntPW=123456
]
Error: Cannot POST /biz/MSFactory/authUsers?UserOID=0830182551&amp;FID=7HD&amp;AID=018&amp;Account=7HD018&amp;FName=%E6%B5%B7%E8%BE%BE&amp;AName=888&amp;Contact=888&amp;Address=888&amp;AInfo=888&amp;OpenUser=1&amp;VidDate=2018-09-01&amp;IntPW=123456

    at Request.<anonymous> (D:\NB\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (D:\NB\node_modules\restler\lib\restler.js:220:12)
    at D:\NB\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.parsers.auto (D:\NB\node_modules\restler\lib\restler.js:394:7)
    at Request.mixin._encode (D:\NB\node_modules\restler\lib\restler.js:195:29)
    at D:\NB\node_modules\restler\lib\restler.js:154:16
    at Request.mixin._decode (D:\NB\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (D:\NB\node_modules\restler\lib\restler.js:147:14)
