[2018-05-14 13:38:18.434] [ERROR] dateFileLog - { Error: listen EADDRINUSE :::2015
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at C:\NB1\yujiang.Foil.Node\src\yjApp.js:218:12
    at C:\NB1\yujiang.Foil.Node.BizServer\biz\org\processAuthority.js:362:8
    at buildAdminProcessAuthority (C:\NB1\yujiang.Foil.Node.BizServer\biz\org\processAuthority.js:158:2)
    at fn (C:\NB1\node_modules\async\lib\async.js:641:34)
    at Immediate._onImmediate (C:\NB1\node_modules\async\lib\async.js:557:34)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 2015 }
[2018-05-14 16:03:34.036] [ERROR] dateFileLog - TypeError: callback is not a function
    at Object.async.whilst (C:\NB1\node_modules\async\lib\async.js:686:13)
    at success (C:\NB1\tm.FGEMS\bizServer\biz\demand\getBalanceSheet.{post}.{m}.js:50:20)
    at Object.exports.safeSuccess (C:\NB1\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB1\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (C:\NB1\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
[2018-05-14 16:03:34.057] [ERROR] dateFileLog - Error: callback is not a function
    at Request.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request._fireSuccess (C:\NB1\node_modules\restler\lib\restler.js:220:12)
    at C:\NB1\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB1\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB1\node_modules\restler\lib\restler.js:195:29)
    at C:\NB1\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB1\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB1\node_modules\restler\lib\restler.js:147:14)
[2018-05-14 16:03:35.312] [ERROR] dateFileLog - TypeError: callback is not a function
    at Object.async.whilst (C:\NB1\node_modules\async\lib\async.js:686:13)
    at success (C:\NB1\tm.FGEMS\bizServer\biz\demand\getBalanceSheet.{post}.{m}.js:50:20)
    at Object.exports.safeSuccess (C:\NB1\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB1\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (C:\NB1\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
[2018-05-14 16:03:35.314] [ERROR] dateFileLog - Error: callback is not a function
    at Request.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request._fireSuccess (C:\NB1\node_modules\restler\lib\restler.js:220:12)
    at C:\NB1\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB1\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB1\node_modules\restler\lib\restler.js:195:29)
    at C:\NB1\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB1\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB1\node_modules\restler\lib\restler.js:147:14)
[2018-05-14 16:06:10.554] [ERROR] dateFileLog - TypeError: callback is not a function
    at Object.async.whilst (C:\NB1\node_modules\async\lib\async.js:686:13)
    at success (C:\NB1\tm.FGEMS\bizServer\biz\demand\getBalanceSheet.{post}.{m}.js:50:20)
    at Object.exports.safeSuccess (C:\NB1\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB1\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (C:\NB1\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
[2018-05-14 16:06:10.557] [ERROR] dateFileLog - Error: callback is not a function
    at Request.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request._fireSuccess (C:\NB1\node_modules\restler\lib\restler.js:220:12)
    at C:\NB1\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB1\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB1\node_modules\restler\lib\restler.js:195:29)
    at C:\NB1\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB1\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB1\node_modules\restler\lib\restler.js:147:14)
[2018-05-14 16:08:27.922] [ERROR] dateFileLog - TypeError: callback is not a function
    at Object.async.whilst (C:\NB1\node_modules\async\lib\async.js:686:13)
    at success (C:\NB1\tm.FGEMS\bizServer\biz\demand\getBalanceSheet.{post}.{m}.js:50:20)
    at Object.exports.safeSuccess (C:\NB1\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB1\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (C:\NB1\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
[2018-05-14 16:08:27.926] [ERROR] dateFileLog - Error: callback is not a function
    at Request.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request._fireSuccess (C:\NB1\node_modules\restler\lib\restler.js:220:12)
    at C:\NB1\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB1\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB1\node_modules\restler\lib\restler.js:195:29)
    at C:\NB1\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB1\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB1\node_modules\restler\lib\restler.js:147:14)
[2018-05-14 16:08:29.789] [ERROR] dateFileLog - TypeError: callback is not a function
    at Object.async.whilst (C:\NB1\node_modules\async\lib\async.js:686:13)
    at success (C:\NB1\tm.FGEMS\bizServer\biz\demand\getBalanceSheet.{post}.{m}.js:50:20)
    at Object.exports.safeSuccess (C:\NB1\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB1\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (C:\NB1\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
[2018-05-14 16:08:29.791] [ERROR] dateFileLog - Error: callback is not a function
    at Request.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request._fireSuccess (C:\NB1\node_modules\restler\lib\restler.js:220:12)
    at C:\NB1\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB1\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB1\node_modules\restler\lib\restler.js:195:29)
    at C:\NB1\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB1\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB1\node_modules\restler\lib\restler.js:147:14)
[2018-05-14 16:09:44.511] [ERROR] dateFileLog - TypeError: callback is not a function
    at Object.async.whilst (C:\NB1\node_modules\async\lib\async.js:686:13)
    at success (C:\NB1\tm.FGEMS\bizServer\biz\demand\getBalanceSheet.{post}.{m}.js:50:20)
    at Object.exports.safeSuccess (C:\NB1\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB1\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (C:\NB1\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
[2018-05-14 16:09:44.519] [ERROR] dateFileLog - Error: callback is not a function
    at Request.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request._fireSuccess (C:\NB1\node_modules\restler\lib\restler.js:220:12)
    at C:\NB1\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB1\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB1\node_modules\restler\lib\restler.js:195:29)
    at C:\NB1\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB1\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB1\node_modules\restler\lib\restler.js:147:14)
[2018-05-14 16:09:45.897] [ERROR] dateFileLog - TypeError: callback is not a function
    at Object.async.whilst (C:\NB1\node_modules\async\lib\async.js:686:13)
    at success (C:\NB1\tm.FGEMS\bizServer\biz\demand\getBalanceSheet.{post}.{m}.js:50:20)
    at Object.exports.safeSuccess (C:\NB1\yujiang.Foil.Node\src\yjError.js:98:13)
    at Object.exports.handleResult (C:\NB1\yujiang.Foil.Node\src\yjError.js:154:12)
    at Query.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjDBService.engine.mysql.js:202:38)
    at bound (domain.js:301:14)
    at Query.runBound [as _callback] (domain.js:314:12)
    at Query.Sequence.end (C:\NB1\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:143:8)
    at Query.EofPacket (C:\NB1\node_modules\mysql\lib\protocol\sequences\Query.js:127:8)
[2018-05-14 16:09:45.907] [ERROR] dateFileLog - Error: callback is not a function
    at Request.<anonymous> (C:\NB1\yujiang.Foil.Node\src\yjREST.engine.remote.restler.js:43:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request._fireSuccess (C:\NB1\node_modules\restler\lib\restler.js:220:12)
    at C:\NB1\node_modules\restler\lib\restler.js:158:20
    at IncomingMessage.auto (C:\NB1\node_modules\restler\lib\restler.js:394:7)
    at Request._encode (C:\NB1\node_modules\restler\lib\restler.js:195:29)
    at C:\NB1\node_modules\restler\lib\restler.js:154:16
    at Request._decode (C:\NB1\node_modules\restler\lib\restler.js:170:7)
    at IncomingMessage.<anonymous> (C:\NB1\node_modules\restler\lib\restler.js:147:14)
